config/routes.rb
Rails.application.routes.draw do
  resource :account do
    resource :join_code, module: :accounts

    scope module: :accounts do
      resource :settings
      resource :entropy_configuration
    end
  end

  resources :users do
    resource :role, module: :users
  end

  resources :collections do
    scope module: :collections do
      resource :subscriptions
      resource :workflow, only: :update
      resource :involvement
      resource :publication
    end

    resources :cards
  end

  namespace :cards do
    resources :previews
    resources :drops
  end

  resources :cards do
    scope module: :cards do
      resource :engagement
      resource :goldness
      resource :image
      resource :pin
      resource :closure
      resource :publish
      resource :reading
      resource :recover
      resource :staging
      resource :watch
      resource :collection, only: :update

      resources :assignments
      resources :taggings

      resources :comments do
        resources :reactions, module: :comments
      end
    end
  end

  resources :notifications do
    scope module: :notifications do
      get "tray", to: "trays#show", on: :collection
      get "settings", to: "settings#show", on: :collection

      post "readings", to: "readings#create_all", on: :collection, as: :read_all
      post "reading", to: "readings#create", on: :member, as: :read
    end
  end

  resource :search
  namespace :searches do
    resources :queries
  end

  resources :filters

  resources :events, only: :index
  namespace :events do
    resources :days
  end

  resources :workflows do
    resources :stages, module: :workflows
  end

  resources :uploads, only: :create
  get "/u/*slug" => "uploads#show", as: :upload

  resources :qr_codes
  get "join/:join_code", to: "users#new", as: :join
  post "join/:join_code", to: "users#create"

  resource :session do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
    resource :launchpad, only: %i[ show update ], controller: "sessions/launchpad"
  end

  namespace :signup do
    get "/" => "accounts#new"
    resources :accounts, only: %i[ new create ]
    get "/session" => "sessions#create" # redirect from Launchpad after mid-signup authentication
    resources :completions, only: %i[ new create ]
  end

  resources :users do
    scope module: :users do
      resource :avatar
    end
  end

  resources :commands do
    scope module: :commands do
      resource :undo, only: :create
    end
  end

  namespace :my do
    resources :pins
  end

  namespace :prompts do
    resources :cards
    resources :collections do
      scope module: :collections do
        resources :users
      end
    end
  end

  namespace :public do
    resources :collections do
      scope module: :collections do
        resources :card_previews
      end
    end
  end

  direct :published_collection do |collection, options|
    route_for :public_collection, collection.publication.key
  end

  resolve "Card" do |card, options|
    route_for :collection_card, card.collection, card, options
  end

  resolve "Comment" do |comment, options|
    options[:anchor] = ActionView::RecordIdentifier.dom_id(comment)
    route_for :collection_card, comment.card.collection, comment.card, options
  end

  resolve "Mention" do |mention, options|
    polymorphic_path(mention.source, options)
  end

  resolve "Notification" do |notification, options|
    polymorphic_path(notification.notifiable_target, options)
  end

  resolve "Event" do |event, options|
    polymorphic_path(event.target, options)
  end

  get "up", to: "rails/health#show", as: :rails_health_check
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "events#index"

  Queenbee.routes(self)

  namespace :admin do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end
end

app/models/card/closeable.rb
module Card::Closeable
  extend ActiveSupport::Concern

  AUTO_CLOSE_AFTER = 30.days
  AUTO_CLOSE_REMINDER_BEFORE = 7.days

  included do
    has_one :closure, dependent: :destroy

    scope :closed, -> { joins(:closure) }
    scope :open, -> { where.missing(:closure) }

    scope :recently_closed_first, -> { closed.order("closures.created_at": :desc) }
    scope :in_auto_closing_collection, -> { joins(:collection).merge(Collection.auto_closing) }
    scope :due_to_be_closed, -> { considering.in_auto_closing_collection.where("last_active_at <= DATETIME('now', '-' || auto_close_period || ' seconds')") }

    delegate :auto_closing?, :auto_close_period, to: :collection
  end

  class_methods do
    def auto_close_all_due
      due_to_be_closed.find_each do |card|
        card.close(user: User.system, reason: "Closed")
      end
    end
  end

  def auto_close_at
    last_active_at + auto_close_period if auto_closing? && last_active_at
  end

  def days_until_close
    (auto_close_at.to_date - Date.current).to_i if auto_close_at
  end

  def closing_soon?
    considering? && Time.current >= auto_close_at - AUTO_CLOSE_REMINDER_BEFORE
  end

  def closed?
    closure.present?
  end

  def open?
    !closed?
  end

  def closed_by
    closure&.user
  end

  def closed_at
    closure&.created_at
  end

  def close(user: Current.user, reason: Closure::Reason.default)
    unless closed?
      transaction do
        create_closure! user: user, reason: reason
        track_event :closed, creator: user
      end
    end
  end

  def reopen
    closure&.destroy
  end
end

app/models/card/searchable.rb
module Card::Searchable
  extend ActiveSupport::Concern

  included do
    include ::Searchable

    searchable_by :title, :description, using: :cards_search_index

    scope :mentioning, ->(query) do
      cards = Card.search(query).select(:id).to_sql
      comments = Comment.search(query).select(:id).to_sql

      left_joins(:comments).where("cards.id in (#{cards}) or comments.id in (#{comments})").distinct
    end

    scope :similar_to, ->(query) do
      cards = Card.search_similar(query).select(:id).to_sql
      comments = Comment.search_similar(query).select(:id).to_sql

      left_joins(:comments).where("cards.id in (#{cards}) or comments.id in (#{comments})").distinct
    end
  end

  private
    # TODO: Temporary until we stabilize the search API
    def title_and_description
      [ title, description.to_plain_text ].join(" ")
    end

    def search_embedding_content
      <<~CONTENT
        Title: #{title}
        Description: #{description.to_plain_text}
        Created by: #{creator.name}}
        Assigned to: #{assignees.map(&:name).join(", ")}}
      CONTENT
    end
end

app/models/user/accessor.rb
module User::Accessor
  extend ActiveSupport::Concern

  included do
    has_many :accesses, dependent: :destroy
    has_many :collections, through: :accesses
    has_many :accessible_cards, through: :collections, source: :cards
    has_many :accessible_comments, through: :accessible_cards, source: :comments

    after_create_commit :grant_access_to_collections
  end

  private
    def grant_access_to_collections
      Access.insert_all Collection.all_access.pluck(:id).collect { |collection_id| { collection_id: collection_id, user_id: id } }
    end
end

app/controllers/cards/readings_controller.rb
class Cards::ReadingsController < ApplicationController
  include CardScoped

  def create
    @notification = Current.user.notifications.find_by(card: @card)
    @notification.read
  end
end

app/controllers/cards/steps_controller.rb
class Cards::StepsController < ApplicationController
  include CardScoped

  before_action :set_step, only: %i[ show edit update destroy ]

  def create
    @step = @card.steps.create!(step_params)
    render_card_replacement
  end

  def show
  end

  def edit
  end

  def update
    @step.update!(step_params)
    render_card_replacement
  end

  def destroy
    @step.destroy!
    render_card_replacement
  end

  private
    def set_step
      @step = @card.steps.find(params[:id])
    end

    def step_params
      params.expect(step: [ :content, :completed ])
    end
end

app/views/cards/index/_collections_filter.html.erb
<%= form_with url: cards_path, method: :get, class: "popup__list",
      data: { controller: "form" } do |form| %>
  <% filter.as_params.except(:collection_ids).each do |key, value| %>
    <%= filter_hidden_field_tag key, value %>
  <% end %>

  <% if Current.user.collections.one? %>
    <%= link_to cards_path(filter.as_params.except(:collection_ids)), class: "popup__group", data: { filter_target: "item", navigable_list_target: "item" } do %>
      <%= tag.div class: "popup__item btn" do %>
        <span class="overflow-ellipsis"><%= Current.user.collections.first.name %></span>
        <span class="txt-ink translucent flex-item-no-shrink flex-item-justify-end"><span class="txt-x-small txt-uppercase">GO TO</span> ›</span>
      <% end %>
    <% end %>
  <% elsif Current.user.collections.many? %>
    <%= link_to cards_path(filter.as_params.except(:collection_ids)), class: "popup__group", data: { filter_target: "item", navigable_list_target: "item" } do %>
      <label class="popup__radio btn txt-xx-small flex-item-no-shrink">
        <input type="checkbox" <%= "checked" if filter.collection_ids.empty? %>>

        <span class="for-screen-reader">
          See everything in all collections
        </span>
        <%= icon_tag "check", size: 18, class: "checked" %>
      </label>
      <%= tag.div class: "popup__item btn" do %>
        <span class="overflow-ellipsis">All collections</span>
        <span class="txt-ink translucent flex-item-no-shrink flex-item-justify-end"><span class="txt-x-small txt-uppercase">GO TO</span> ›</span>
      <% end %>
    <% end %>

    <% Current.user.collections.ordered_by_recently_accessed.each do |collection| %>
      <li class="popup__group" data-filter-target="item" data-navigable-list-target="item">
        <label class="popup__radio btn txt-xx-small flex-item-no-shrink">
          <%= form.check_box "collection_ids[]", {
                checked: filter.collections.include?(collection),
                data: { action: "change->form#submit" },
                include_hidden: false,
          }, collection.id %>

          <span class="for-screen-reader">
            Toggle filter for <%= collection.name %>
          </span>
          <%= icon_tag "check", size: 18, class: "checked" %>
        </label>

        <%= link_to cards_path(collection_ids: [ collection ]), class: "popup__item btn" do %>
          <span class="overflow-ellipsis"><%= collection.name %></span>
          <span class="translucent flex-item-no-shrink flex-item-justify-end"> ›</span>
        <% end %>
      </li>
    <% end %>
  <% end %>
<% end %>