config/routes.rb
Rails.application.routes.draw do
  resource :account do
    resource :join_code, module: :accounts

    scope module: :accounts do
      resource :settings
      resource :entropy_configuration
    end
  end

  resources :users do
    resource :role, module: :users
  end

  resources :collections do
    scope module: :collections do
      resource :subscriptions
      resource :workflow, only: :update
      resource :involvement
      resource :publication
    end

    resources :cards
  end

  namespace :cards do
    resources :previews
    resources :drops
  end

  resources :cards do
    scope module: :cards do
      resource :engagement
      resource :goldness
      resource :image
      resource :pin
      resource :closure
      resource :publish
      resource :reading
      resource :recover
      resource :staging
      resource :watch
      resource :collection, only: :update

      resources :assignments
      resources :taggings

      resources :comments do
        resources :reactions, module: :comments
      end
    end
  end

  resources :notifications do
    scope module: :notifications do
      get "tray", to: "trays#show", on: :collection
      get "settings", to: "settings#show", on: :collection

      post "readings", to: "readings#create_all", on: :collection, as: :read_all
      post "reading", to: "readings#create", on: :member, as: :read
    end
  end

  resource :search
  namespace :searches do
    resources :queries
  end

  resources :filters

  resources :events, only: :index
  namespace :events do
    resources :days
  end

  resources :workflows do
    resources :stages, module: :workflows
  end

  resources :uploads, only: :create
  get "/u/*slug" => "uploads#show", as: :upload

  resources :qr_codes
  get "join/:join_code", to: "users#new", as: :join
  post "join/:join_code", to: "users#create"

  resource :session do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
    resource :launchpad, only: %i[ show update ], controller: "sessions/launchpad"
  end

  namespace :signup do
    get "/" => "accounts#new"
    resources :accounts, only: %i[ new create ]
    get "/session" => "sessions#create" # redirect from Launchpad after mid-signup authentication
    resources :completions, only: %i[ new create ]
  end

  resources :users do
    scope module: :users do
      resource :avatar
    end
  end

  resources :commands do
    scope module: :commands do
      resource :undo, only: :create
    end
  end

  namespace :my do
    resources :pins
  end

  namespace :prompts do
    resources :cards
    resources :collections do
      scope module: :collections do
        resources :users
      end
    end
  end

  namespace :public do
    resources :collections do
      scope module: :collections do
        resources :card_previews
      end
    end
  end

  direct :published_collection do |collection, options|
    route_for :public_collection, collection.publication.key
  end

  resolve "Card" do |card, options|
    route_for :collection_card, card.collection, card, options
  end

  resolve "Comment" do |comment, options|
    options[:anchor] = ActionView::RecordIdentifier.dom_id(comment)
    route_for :collection_card, comment.card.collection, comment.card, options
  end

  resolve "Mention" do |mention, options|
    polymorphic_path(mention.source, options)
  end

  resolve "Notification" do |notification, options|
    polymorphic_path(notification.notifiable_target, options)
  end

  resolve "Event" do |event, options|
    polymorphic_path(event.target, options)
  end

  get "up", to: "rails/health#show", as: :rails_health_check
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "events#index"

  Queenbee.routes(self)

  namespace :admin do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :card
  belongs_to :resource, polymorphic: true

  scope :unread, -> { where(read_at: nil) }
  scope :read, -> { where.not(read_at: nil) }
  scope :ordered, -> { order(read_at: :desc, created_at: :desc) }

  delegate :creator, to: :event
  after_create_commit :broadcast_unread

  def self.read_all
    update!(read_at: Time.current)
  end

  def read
    update!(read_at: Time.current)
  end

  def read?
    read_at.present?
  end

  private
    def broadcast_unread
      broadcast_prepend_later_to user, :notifications, target: "notifications"
    end
end

app/controllers/notifications/readings_controller.rb
class Notifications::ReadingsController < ApplicationController
  def create
    @notification = Current.user.notifications.find(params[:id])
    @notification.read
  end

  def create_all
    Current.user.notifications.unread.read_all
    redirect_to notifications_path
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @unread = Current.user.notifications.unread.ordered unless current_page_param
    set_page_and_extract_portion_from Current.user.notifications.read.ordered

    respond_to do |format|
      format.turbo_stream if current_page_param # Allows read-all action to side step pagination
      format.html
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def event_notification_title(event)
    case event_notification_action(event)
    when "comment_created" then "RE: #{card_notification_title(event.eventable.card)}"
    else card_notification_title(event.eventable)
    end
  end

  def event_notification_body(event)
    name = event.creator.name

    case event_notification_action(event)
    when "card_closed"
      if event.card.closure
        "Closed as “#{event.card.closure.reason}” by #{name}"
      else
        "Closed by #{name}"
      end
    when "card_reopened" then "Reopened by #{name}"
    when "card_published" then "Added by #{name}"
    when "comment_created" then comment_notification_body(event)
    when "card_assigned" then "Assigned to #{event.assignees.none? ? "self" : event.assignees.pluck(:name).to_sentence}"
    else name
    end
  end

  def notification_tag(notification, &)
    tag.div id: dom_id(notification), class: "tray__item", data: { navigable_list_target: "item" } do
      concat(
        link_to(notification,
          class: [ "card card--notification", { "card--closed": notification.card.closed? }, { "unread": !notification.read? } ],
          data: { turbo_frame: "_top", badge_target: "unread", action: "badge#update" },
          style: { "--card-color:": notification.card.color },
          &)
      )
    end
  end

  def notification_toggle_read_button(notification)
    if notification.read?
      button_to read_notification_path(notification),
          method: :delete,
          class: "card__notification-unread-indicator btn btn--circle borderless",
          title: "Mark as unread",
          data: { action: "form#submit:stop badge#update:stop", form_target: "submit" },
          form: { data: { controller: "form" } } do
        concat(icon_tag("unseen"))
        concat(tag.span("Mark as unread", class: "for-screen-reader"))
      end
    else
      button_to read_notification_path(notification),
          class: "card__notification-unread-indicator btn btn--circle borderless",
          title: "Mark as read",
          data: { action: "form#submit:stop badge#update:stop", form_target: "submit" },
          form: { data: { controller: "form" } } do
        concat(icon_tag("remove-med"))
        concat(tag.span("Mark as read", class: "for-screen-reader"))
      end
    end
  end

  def notifications_next_page_link(page)
    unless @page.last?
      tag.div id: "next_page", data: { controller: "fetch-on-visible", fetch_on_visible_url_value: notifications_path(page: @page.next_param) }
    end
  end

  private
    def event_notification_action(event)
      if event.action.card_published? && event.eventable.assigned_to?(event.creator)
        "card_assigned"
      else
        event.action
      end
    end

    def comment_notification_body(event)
      comment = event.eventable
      strip_tags(comment.body.to_s).truncate(200)
    end

    def card_notification_title(card)
      card.title.presence || "Card #{card.id}"
    end
end

app/views/notifications/_tray.html.erb
<%= turbo_stream_from Current.user, :notifications %>

<dialog class="tray notification-tray"
    data-controller="dialog" data-dialog-modal-value="false" data-dialog-target="dialog"
    data-action="keydown.esc->dialog#close:stop click@document->dialog#closeOnClickOutside">
  <%= turbo_frame_tag "notifications", src: tray_notifications_path %>

  <%= link_to notifications_path, class: "tray__overflow border-radius txt-normal", data: { action: "click->dialog#close" } do %>
    <div class="notification__content border-radius shadow fill-white flex align-center txt-align-center gap full-width border txt-ink txt-small">
      <div class="flex flex-column txt-tight-lines min-width flex-item-grow">
        <strong>+ More…</strong>
      </div>
    </div>
  <% end %>

  <div class="tray__actions notification-tray__actions border border-radius">
    <%= button_to read_all_notifications_path,
          class: "notification-tray__read_action btn btn--reversed fill-transparent borderless flex-item-justify-start shadow txt-xx-small",
          data: { action: "click->dialog#close", turbo_frame: "notifications" } do %>
      <%= icon_tag "check" %> <span class="for-screen-reader">Mark all read</span>
    <% end %>

    <%= link_to tag.span("Notifications"), notifications_path,
          class: "btn btn--reversed borderless fill-transparent translucent shadow center txt-uppercase txt-x-small",
          data: { action: "click->dialog#close" } %>

    <span class="btn btn--placeholder txt-xx-small borderless"></span>
  </div>

  <button class="tray__expander" data-action="dialog#toggle" aria-label="Expand notifications stack"></button>
</dialog>

app/views/notifications/index.html.erb
<% @page_title = "Notifications" %>
<% @hide_footer_frames = true %>

<% content_for :header do %>
  <nav class="header">
    <div class="header__actions header__actions--start">
      <%= link_to_home class: "flex-item-justify-start" %>
    </div>

    <h1 class="header__title"><%= @page_title %></h1>

    <div class="header__actions header__actions--end">
      <%= link_to settings_notifications_path, class: "btn" do %>
        <%= icon_tag "settings" %> <span class="for-screen-reader">Notification settings</span>
      <% end %>
    </div>
  </nav>
<% end %>

<div data-controller="badge navigable-list" data-badge-unread-class="unread" data-action="keydown@document->navigable-list#navigate" data-navigable-list-actionable-items-value="true"
      data-navigable-list-focus-on-selection-value="false">
  <section class="notifications-list panel center borderless unpad flex flex-column gap-half">
    <% if @unread.any? %>
      <div class="flex align-center justify-space-between margin-block-start margin-block-end-half">
        <h2 class="txt-medium txt-uppercase txt-alert">New for you</h2>
        <%= button_to "Mark all as read", read_all_notifications_path, class: "btn txt-small", form: { data: { turbo: false } }, data: { action: "badge#clear" } %>
      </div>
    <% else %>
      <div class="notifications-list__empty-message pad border-radius border translucent" style="--border-style: dashed; --border-color: var(--color-ink); --border-radius: 0.2em;">
        <strong>Nothing new for you.</strong>
      </div>
    <% end %>

    <div id="notifications_list" contents>
      <%= render partial: "notifications/notification", collection: @unread, cached: true %>
    </div>
  </section>

  <section class="notifications-list notifications-list--read panel center borderless unpad flex flex-column gap-half margin-block-start">
    <h2 class="txt-medium margin-block-start-double margin-block-end-half txt-uppercase translucent">Previously seen</h2>

    <div id="notifications_list_read" contents>
      <%= render partial: "notifications/notification", collection: @page.records, cached: true %>
    </div>
  </section>
</div>

<%= notifications_next_page_link(@page) if @page.records.any? %>

app/views/notifications/index.turbo_stream.erb
<%= turbo_stream.append :notifications_list_read, partial: "notifications/notification", collection: @page.records %>
<%= turbo_stream.replace :next_page, notifications_next_page_link(@page) %>