config/routes.rb
Rails.application.routes.draw do
  resource :account do
    resource :join_code, module: :accounts

    scope module: :accounts do
      resource :settings
      resource :entropy_configuration
    end
  end

  resources :users do
    resource :role, module: :users
  end

  resources :collections do
    scope module: :collections do
      resource :subscriptions
      resource :workflow, only: :update
      resource :involvement
      resource :publication
    end

    resources :cards
  end

  namespace :cards do
    resources :previews
    resources :drops
  end

  resources :cards do
    scope module: :cards do
      resource :engagement
      resource :goldness
      resource :image
      resource :pin
      resource :closure
      resource :publish
      resource :reading
      resource :recover
      resource :staging
      resource :watch
      resource :collection, only: :update

      resources :assignments
      resources :taggings

      resources :comments do
        resources :reactions, module: :comments
      end
    end
  end

  resources :notifications do
    scope module: :notifications do
      get "tray", to: "trays#show", on: :collection
      get "settings", to: "settings#show", on: :collection

      post "readings", to: "readings#create_all", on: :collection, as: :read_all
      post "reading", to: "readings#create", on: :member, as: :read
    end
  end

  resource :search
  namespace :searches do
    resources :queries
  end

  resources :filters

  resources :events, only: :index
  namespace :events do
    resources :days
  end

  resources :workflows do
    resources :stages, module: :workflows
  end

  resources :uploads, only: :create
  get "/u/*slug" => "uploads#show", as: :upload

  resources :qr_codes
  get "join/:join_code", to: "users#new", as: :join
  post "join/:join_code", to: "users#create"

  resource :session do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
    resource :launchpad, only: %i[ show update ], controller: "sessions/launchpad"
  end

  namespace :signup do
    get "/" => "accounts#new"
    resources :accounts, only: %i[ new create ]
    get "/session" => "sessions#create" # redirect from Launchpad after mid-signup authentication
    resources :completions, only: %i[ new create ]
  end

  resources :users do
    scope module: :users do
      resource :avatar
    end
  end

  resources :commands do
    scope module: :commands do
      resource :undo, only: :create
    end
  end

  namespace :my do
    resources :pins
  end

  namespace :prompts do
    resources :cards
    resources :collections do
      scope module: :collections do
        resources :users
      end
    end
  end

  namespace :public do
    resources :collections do
      scope module: :collections do
        resources :card_previews
      end
    end
  end

  direct :published_collection do |collection, options|
    route_for :public_collection, collection.publication.key
  end

  resolve "Card" do |card, options|
    route_for :collection_card, card.collection, card, options
  end

  resolve "Comment" do |comment, options|
    options[:anchor] = ActionView::RecordIdentifier.dom_id(comment)
    route_for :collection_card, comment.card.collection, comment.card, options
  end

  resolve "Mention" do |mention, options|
    polymorphic_path(mention.source, options)
  end

  resolve "Notification" do |notification, options|
    polymorphic_path(notification.notifiable_target, options)
  end

  resolve "Event" do |event, options|
    polymorphic_path(event.target, options)
  end

  get "up", to: "rails/health#show", as: :rails_health_check
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "events#index"

  Queenbee.routes(self)

  namespace :admin do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end
end

app/models/command/search.rb
class Command::Search < Command
  store_accessor :data, :terms

  def title
    "Search '#{terms}'"
  end

  def execute
    redirect_to search_path(q: terms)
  end
end

app/models/search.rb
class Search
  attr_reader :user, :query

  HIGHLIGHT_OPENING_MARK = "<mark class=\"circled-text\"><span></span>"
  HIGHLIGHT_CLOSING_MARK = "</mark>"

  def self.table_name_prefix
    "search_"
  end

  def initialize(user, query)
    @user = user
    @query = Query.wrap(query)
  end

  def results
    return Search::Result.none unless query.valid?

    cards = user.accessible_cards.search(query)
      .select([
        "cards.id as card_id",
        "null as comment_id",
        "highlight(cards_search_index, 0, '#{HIGHLIGHT_OPENING_MARK}', '#{HIGHLIGHT_CLOSING_MARK}') AS card_title",
        "snippet(cards_search_index, 1, '#{HIGHLIGHT_OPENING_MARK}', '#{HIGHLIGHT_CLOSING_MARK}', '...', 20) AS card_description",
        "null as comment_body",
        "collections.name as collection_name",
        "cards.creator_id",
        "bm25(cards_search_index, 10.0, 2.0) AS score"
      ].join(","))

    comments = user.accessible_comments.search(query)
      .select([
        "comments.card_id as card_id",
        "comments.id as comment_id",
        "cards.title AS card_title",
        "null AS card_description",
        "snippet(comments_search_index, 0, '#{HIGHLIGHT_OPENING_MARK}', '#{HIGHLIGHT_CLOSING_MARK}', '...', 20) AS comment_body",
        "collections.name as collection_name",
        "comments.creator_id",
        "bm25(comments_search_index, 1.0) AS score"
      ].join(","))

    union_sql = "(#{cards.to_sql} UNION #{comments.to_sql}) as search_results"
    Search::Result.from(union_sql).order(score: :desc)
  end
end

app/models/search/query.rb
class Search::Query < ApplicationRecord
  validates :terms, presence: true
  before_validation :sanitize_terms

  class << self
    def wrap(query)
      if query.is_a?(self)
        query
      else
        self.new(terms: query)
      end
    end
  end

  alias_attribute :to_s, :terms

  private
    def sanitize_terms
      self.terms = sanitize(terms)
    end

    def sanitize(terms)
      if terms.present?
        terms = remove_invalid_search_characters(self.terms)
        terms = remove_unbalanced_quotes(terms)
        terms.presence
      else
        terms
      end
    end

    def remove_invalid_search_characters(terms)
      terms.gsub(/[^\w"]/, " ")
    end

    def remove_unbalanced_quotes(terms)
      if terms.count("\"").even?
        terms
      else
        terms.gsub("\"", " ")
      end
    end
end

app/models/search/result.rb
class Search::Result < ApplicationRecord
  belongs_to :creator, class_name: "User"
  belongs_to :card, foreign_key: :card_id, optional: true
  belongs_to :comment, foreign_key: :comment_id, optional: true

  def source
    comment_id.present? ? comment : card
  end

  def readonly?
    true
  end
end

app/controllers/concerns/search/query_terms_scoped.rb
module Search::QueryTermsScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_query_terms
  end

  private
    def set_query_terms
      @query_terms = params[:q]
    end
end

app/controllers/searches/queries_controller.rb
class Searches::QueriesController < ApplicationController
  include Search::QueryTermsScoped

  def create
    Current.user.remember_search(@query_terms)
    head :ok
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  include Search::QueryTermsScoped

  def show
    @search_results = Current.user.search(@query_terms).limit(50)
    @recent_search_queries = Current.user.search_queries.order(created_at: :desc).limit(10)
  end
end

app/views/searches/_form.html.erb
<%= form_with url: search_path, method: :get, class: "search__form" do |form| %>
  <%= text_field_tag :q, query_terms, class: "search__form-input input", type: "search", placeholder: "What are you looking for?" %>
  <%= icon_tag "search", class: "search__form-icon" %>
<% end %>

app/views/searches/_result.html.erb
<li>
  <%= link_to result.source, class: "card card--search" do %>
    <header class="card__header">
      <label class="card__collection flex align-center">
        <span class="card__id"><%= result.card_id %></span>
        <span class="card__collection-name">
        <span class="overflow-ellipsis"><%= result.collection_name %></span>
      </span>
      </label>
    </header>

    <div class="card__body justify-space-between">
      <div class="card__content">
        <h3 class="card__title">
          <%= result.card_title&.html_safe %>
        </h3>

        <% if result.card_description.present? %>
          <div class="search__excerpt">
            <%= result.card_description.html_safe %>
          </div>
        <% else
             if result.comment_body.present? %>
            <div class="search__excerpt search__excerpt--comment">
              <%= avatar_preview_tag result.creator %>
              <div>
                <%= result.comment_body.html_safe %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</li>

app/views/searches/_result_mockup.html.erb
<div class="card card--search">
  <header class="card__header">
    <label class="card__collection flex align-center">
      <span class="card__id">864</span>
      <span class="card__collection-name">
        <span class="overflow-ellipsis"><%= collection %></span>
      </span>
    </label>
  </header>

  <div class="card__body justify-space-between">
    <div class="card__content">
      <h3 class="card__title">
        <%= title.html_safe %>
      </h3>
      <%= yield %>
    </div>
  </div>
</div>

app/views/searches/_search_query.html.erb
<li>
  <%= link_to search_query.terms, search_path(q: search_query.terms), class: "btn txt-small" %>
</li>

app/views/searches/show.html.erb
<% @page_title = "Search" %>

<% content_for :header do %>
  <nav>
    <%= link_to_back fallback_path: root_path %>

    <header class="center">
      <h1 class="txt-large margin-none"><%= @page_title %></h1>
    </header>

    <div class="btn btn--placeholder flex-item-justify-end"></div>
  </nav>
<% end %>

<%= auto_submit_form_with url: searches_queries_path(q: @query_terms), method: :post %>

<section class="search">
  <%= render "searches/form", query_terms: @query_terms %>

  <div class="search__results">
    <% if @query_terms.present? && @search_results.none? %>
      <div class="search__empty">
        No search results
      </div>
    <% end %>

    <ul class="search__list">
      <%= render partial: "searches/result", collection: @search_results %>
    </ul>
  </div>

  <aside class="search__history">
    <h3>Your recent searches…</h3>
    <ul class="search__list">
      <%= render partial: "searches/search_query", collection: @recent_search_queries.first(10) %>
    </ul>
  </aside>
</section>