config/routes.rb
Rails.application.routes.draw do
  resource :account do
    resource :join_code, module: :accounts

    scope module: :accounts do
      resource :settings
      resource :entropy_configuration
    end
  end

  resources :users do
    resource :role, module: :users
  end

  resources :collections do
    scope module: :collections do
      resource :subscriptions
      resource :workflow, only: :update
      resource :involvement
      resource :publication
    end

    resources :cards
  end

  namespace :cards do
    resources :previews
    resources :drops
  end

  resources :cards do
    scope module: :cards do
      resource :engagement
      resource :goldness
      resource :image
      resource :pin
      resource :closure
      resource :publish
      resource :reading
      resource :recover
      resource :staging
      resource :watch
      resource :collection, only: :update

      resources :assignments
      resources :taggings

      resources :comments do
        resources :reactions, module: :comments
      end
    end
  end

  resources :notifications do
    scope module: :notifications do
      get "tray", to: "trays#show", on: :collection
      get "settings", to: "settings#show", on: :collection

      post "readings", to: "readings#create_all", on: :collection, as: :read_all
      post "reading", to: "readings#create", on: :member, as: :read
    end
  end

  resource :search
  namespace :searches do
    resources :queries
  end

  resources :filters

  resources :events, only: :index
  namespace :events do
    resources :days
  end

  resources :workflows do
    resources :stages, module: :workflows
  end

  resources :uploads, only: :create
  get "/u/*slug" => "uploads#show", as: :upload

  resources :qr_codes
  get "join/:join_code", to: "users#new", as: :join
  post "join/:join_code", to: "users#create"

  resource :session do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
    resource :launchpad, only: %i[ show update ], controller: "sessions/launchpad"
  end

  namespace :signup do
    get "/" => "accounts#new"
    resources :accounts, only: %i[ new create ]
    get "/session" => "sessions#create" # redirect from Launchpad after mid-signup authentication
    resources :completions, only: %i[ new create ]
  end

  resources :users do
    scope module: :users do
      resource :avatar
    end
  end

  resources :commands do
    scope module: :commands do
      resource :undo, only: :create
    end
  end

  namespace :my do
    resources :pins
  end

  namespace :prompts do
    resources :cards
    resources :collections do
      scope module: :collections do
        resources :users
      end
    end
  end

  namespace :public do
    resources :collections do
      scope module: :collections do
        resources :card_previews
      end
    end
  end

  direct :published_collection do |collection, options|
    route_for :public_collection, collection.publication.key
  end

  resolve "Card" do |card, options|
    route_for :collection_card, card.collection, card, options
  end

  resolve "Comment" do |comment, options|
    options[:anchor] = ActionView::RecordIdentifier.dom_id(comment)
    route_for :collection_card, comment.card.collection, comment.card, options
  end

  resolve "Mention" do |mention, options|
    polymorphic_path(mention.source, options)
  end

  resolve "Notification" do |notification, options|
    polymorphic_path(notification.notifiable_target, options)
  end

  resolve "Event" do |event, options|
    polymorphic_path(event.target, options)
  end

  get "up", to: "rails/health#show", as: :rails_health_check
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "events#index"

  Queenbee.routes(self)

  namespace :admin do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end
end

app/models/card/closeable.rb
module Card::Closeable
  extend ActiveSupport::Concern

  AUTO_CLOSE_AFTER = 30.days
  AUTO_CLOSE_REMINDER_BEFORE = 7.days

  included do
    has_one :closure, dependent: :destroy

    scope :closed, -> { joins(:closure) }
    scope :open, -> { where.missing(:closure) }

    scope :recently_closed_first, -> { closed.order("closures.created_at": :desc) }
    scope :in_auto_closing_collection, -> { joins(:collection).merge(Collection.auto_closing) }
    scope :due_to_be_closed, -> { considering.in_auto_closing_collection.where("last_active_at <= DATETIME('now', '-' || auto_close_period || ' seconds')") }

    delegate :auto_closing?, :auto_close_period, to: :collection
  end

  class_methods do
    def auto_close_all_due
      due_to_be_closed.find_each do |card|
        card.close(user: User.system, reason: "Closed")
      end
    end
  end

  def auto_close_at
    last_active_at + auto_close_period if auto_closing? && last_active_at
  end

  def days_until_close
    (auto_close_at.to_date - Date.current).to_i if auto_close_at
  end

  def closing_soon?
    considering? && Time.current >= auto_close_at - AUTO_CLOSE_REMINDER_BEFORE
  end

  def closed?
    closure.present?
  end

  def open?
    !closed?
  end

  def closed_by
    closure&.user
  end

  def closed_at
    closure&.created_at
  end

  def close(user: Current.user, reason: Closure::Reason.default)
    unless closed?
      transaction do
        create_closure! user: user, reason: reason
        track_event :closed, creator: user
      end
    end
  end

  def reopen
    closure&.destroy
  end
end

app/models/card/searchable.rb
module Card::Searchable
  extend ActiveSupport::Concern

  included do
    include ::Searchable

    searchable_by :title, :description, using: :cards_search_index

    scope :mentioning, ->(query) do
      cards = Card.search(query).select(:id).to_sql
      comments = Comment.search(query).select(:id).to_sql

      left_joins(:comments).where("cards.id in (#{cards}) or comments.id in (#{comments})").distinct
    end

    scope :similar_to, ->(query) do
      cards = Card.search_similar(query).select(:id).to_sql
      comments = Comment.search_similar(query).select(:id).to_sql

      left_joins(:comments).where("cards.id in (#{cards}) or comments.id in (#{comments})").distinct
    end
  end

  private
    # TODO: Temporary until we stabilize the search API
    def title_and_description
      [ title, description.to_plain_text ].join(" ")
    end

    def search_embedding_content
      <<~CONTENT
        Title: #{title}
        Description: #{description.to_plain_text}
        Created by: #{creator.name}}
        Assigned to: #{assignees.map(&:name).join(", ")}}
      CONTENT
    end
end

app/controllers/cards/readings_controller.rb
class Cards::ReadingsController < ApplicationController
  include CardScoped

  def create
    @notification = Current.user.notifications.find_by(card: @card)
    @notification.read
  end
end

app/controllers/cards/steps_controller.rb
class Cards::StepsController < ApplicationController
  include CardScoped

  before_action :set_step, only: %i[ show edit update destroy ]

  def create
    @step = @card.steps.create!(step_params)
    render_card_replacement
  end

  def show
  end

  def edit
  end

  def update
    @step.update!(step_params)
    render_card_replacement
  end

  def destroy
    @step.destroy!
    render_card_replacement
  end

  private
    def set_step
      @step = @card.steps.find(params[:id])
    end

    def step_params
      params.expect(step: [ :content, :completed ])
    end
end

app/views/cards/_collection_settings.html.erb
<%= link_to edit_collection_path(collection), class: "btn tooltip" do %>
  <%= icon_tag "settings" %>
  <span class="for-screen-reader">Settings for <%= collection.name %></span>
<% end %>

app/views/cards/index.html.erb
<% @page_title = @user_filtering.selected_collections_label %>

<%= render "filters/broadcasts", filter: @filter %>

<% content_for :head do %>
  <%= tag.meta property: "og:title", content: @page_title %>
  <%= tag.meta property: "og:description", content: Account.sole.name %>
  <%= tag.meta property: "og:url", content: cards_url(@filter.as_params) %>
<% end %>

<% content_for :header do %>
  <%= render "filters/menu", user_filtering: @user_filtering %>

  <div class="header__actions header__actions--start">
    <% if collection = @filter.single_collection %>
      <%= access_involvement_advance_button collection, Current.user %>
    <% end %>
  </div>

  <h1 class="header__title overflow-ellipsis" style="view-transistion-name: card-collection-title">
    <%= @user_filtering.selected_collections_label %>
  </h1>

  <div class="header__actions header__actions--end">
    <% if collection = @filter.single_collection %>
      <%= render "cards/collection_settings", collection: collection %>
    <% end %>
  </div>
<% end %>

<%= render "filters/settings", user_filtering: @user_filtering %>

<%= tag.div data: {
      controller: "drag-and-drop",
      drag_and_drop_dragged_item_class: "drag-and-drop__dragged-item",
      drag_and_drop_hover_container_class: "drag-and-drop__hover-container",
      drag_and_drop_url_value: cards_drops_path(**@filter.as_params),
      action: "
        dragstart->drag-and-drop#dragStart
        dragover->drag-and-drop#dragOver
        drop->drag-and-drop#drop
        dragend->drag-and-drop#dragEnd" } do %>
  <div class="card-columns" data-controller="related-element" data-related-element-highlight-class="cards--related">
    <%= render "cards/index/engagement/on_deck", **@on_deck.to_h %>
    <%= render "cards/index/engagement/considering", **@considering.to_h %>
    <%= render "cards/index/engagement/doing", **@doing.to_h %>
  </div>

  <%= render "cards/index/engagement/closed", **@closed.to_h %>
<% end %>